=== 10-Tyger-17/M.A.E.K.-LMS-/Website/MAEK_LMS/public_html/MAEK_LMS.xsd
<?xml version="1.0"?>
<xs:schema version="1.0"
       	xmlns:xs="http://www.w3.org/2001/XMLSchema"
       	elementFormDefault="qualified">

	<xs:element name="maek">
            <xs:complexType>
                    <xs:sequence>
                        
                        <xs:element name="clients">
                            <xs:complexType>
                                    <xs:sequence>
                                        
                                            <xs:element name="client" maxOccurs="unbounded">
                                                <xs:complexType>
                                                        <xs:sequence>
                                                            <xs:element name="name" type="xs:string"/>
                                                            <xs:element name="vip" minOccurs="0" type="xs:string"/>
                                                            <xs:choice>
                                                                    <xs:element name="woman" type="xs:string"/>
                                                                    <xs:element name="man" type="xs:string"/>
                                                            </xs:choice>

                                                            <xs:element name="phone">
                                                                    <xs:simpleType>
                                                                    <xs:restriction base="xs:string">
                                                                            <xs:pattern value="[0-9]{9}"/>
                                                                    </xs:restriction>
                                                                    </xs:simpleType>
                                                            </xs:element>
                                                        </xs:sequence>
                                                        
                                                        <xs:attribute name="image" type="xs:string"/>
                                                        <xs:attribute name="dni">
                                                            <xs:simpleType>
                                                                <xs:restriction base="xs:string">
                                                                    <xs:pattern value="[1-9]{8}[A-Z]"/>
                                                                </xs:restriction>
                                                            </xs:simpleType>
                                                        </xs:attribute>
                                                </xs:complexType>
                                            </xs:element>
                                            
                                    </xs:sequence>
                                </xs:complexType>
                        </xs:element>
                        
                        <xs:element name="products">
                                <xs:complexType>
                                    <xs:sequence>
                                            <xs:element name="product">
                                                <xs:complexType>
                                                        <xs:sequence>
                                                            <xs:element name="name" type="xs:string"/>
                                                            <xs:element name="price" type="xs:double"/>
                                                        </xs:sequence>
                                                        <xs:attribute name="id" type="xs:string" use="required"/>
                                                </xs:complexType>
                                            </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                        </xs:element>
                        
                    </xs:sequence>
            </xs:complexType>
	</xs:element>

</xs:schema>

=== 10-Tyger-17/M.A.E.K.-LMS-/Website/XML/MAEK_LMS.xml
<?xml-stylesheet type="text/xsl" href="../XSLT/MAEK_LMS.xsl"?>
<maek xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../XSD/MAEK_LMS.xsd">
  <clients>
    <client dni="12345678A" image="http://">
      <name>Carmen</name>
      <female/>
      <phone>123456789</phone>
    </client>
    
  </clients>
  <products>
    <product id="123A">
      <name>GPU</name>
      <price>12</price>
    </product>
  </products>
</maek>
